// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(bunnyshell_coreFFI)
import bunnyshell_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_bunnyshell_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_bunnyshell_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol PtyManagerProtocol : AnyObject {
    
    func close(id: UInt32) throws 
    
    func resize(id: UInt32, cols: UInt16, rows: UInt16) throws 
    
    func spawn(id: UInt32, cols: UInt16, rows: UInt16, cwd: String?, callback: PtyCallback) throws 
    
    func write(id: UInt32, data: Data) throws 
    
}

open class PtyManager:
    PtyManagerProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_bunnyshell_core_fn_clone_ptymanager(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_bunnyshell_core_fn_constructor_ptymanager_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_bunnyshell_core_fn_free_ptymanager(pointer, $0) }
    }

    

    
open func close(id: UInt32)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_method_ptymanager_close(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(id),$0
    )
}
}
    
open func resize(id: UInt32, cols: UInt16, rows: UInt16)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_method_ptymanager_resize(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(id),
        FfiConverterUInt16.lower(cols),
        FfiConverterUInt16.lower(rows),$0
    )
}
}
    
open func spawn(id: UInt32, cols: UInt16, rows: UInt16, cwd: String?, callback: PtyCallback)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_method_ptymanager_spawn(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(id),
        FfiConverterUInt16.lower(cols),
        FfiConverterUInt16.lower(rows),
        FfiConverterOptionString.lower(cwd),
        FfiConverterCallbackInterfacePtyCallback.lower(callback),$0
    )
}
}
    
open func write(id: UInt32, data: Data)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_method_ptymanager_write(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(id),
        FfiConverterData.lower(data),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePtyManager: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = PtyManager

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> PtyManager {
        return PtyManager(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: PtyManager) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PtyManager {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: PtyManager, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePtyManager_lift(_ pointer: UnsafeMutableRawPointer) throws -> PtyManager {
    return try FfiConverterTypePtyManager.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePtyManager_lower(_ value: PtyManager) -> UnsafeMutableRawPointer {
    return FfiConverterTypePtyManager.lower(value)
}




public protocol TerminalRendererProtocol : AnyObject {
    
    func render(lines: [String]) throws 
    
    func resize(width: UInt32, height: UInt32) 
    
}

open class TerminalRenderer:
    TerminalRendererProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_bunnyshell_core_fn_clone_terminalrenderer(self.pointer, $0) }
    }
public convenience init(nsviewPtr: UInt64, width: UInt32, height: UInt32)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_constructor_terminalrenderer_new(
        FfiConverterUInt64.lower(nsviewPtr),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_bunnyshell_core_fn_free_terminalrenderer(pointer, $0) }
    }

    

    
open func render(lines: [String])throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_method_terminalrenderer_render(self.uniffiClonePointer(),
        FfiConverterSequenceString.lower(lines),$0
    )
}
}
    
open func resize(width: UInt32, height: UInt32) {try! rustCall() {
    uniffi_bunnyshell_core_fn_method_terminalrenderer_resize(self.uniffiClonePointer(),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),$0
    )
}
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTerminalRenderer: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = TerminalRenderer

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> TerminalRenderer {
        return TerminalRenderer(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: TerminalRenderer) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TerminalRenderer {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: TerminalRenderer, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTerminalRenderer_lift(_ pointer: UnsafeMutableRawPointer) throws -> TerminalRenderer {
    return try FfiConverterTypeTerminalRenderer.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTerminalRenderer_lower(_ value: TerminalRenderer) -> UnsafeMutableRawPointer {
    return FfiConverterTypeTerminalRenderer.lower(value)
}


public struct DirEntry {
    public var name: String
    public var kind: EntryKind
    public var size: UInt64
    public var mtime: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, kind: EntryKind, size: UInt64, mtime: UInt64) {
        self.name = name
        self.kind = kind
        self.size = size
        self.mtime = mtime
    }
}



extension DirEntry: Equatable, Hashable {
    public static func ==(lhs: DirEntry, rhs: DirEntry) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        if lhs.mtime != rhs.mtime {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(kind)
        hasher.combine(size)
        hasher.combine(mtime)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDirEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DirEntry {
        return
            try DirEntry(
                name: FfiConverterString.read(from: &buf), 
                kind: FfiConverterTypeEntryKind.read(from: &buf), 
                size: FfiConverterUInt64.read(from: &buf), 
                mtime: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: DirEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeEntryKind.write(value.kind, into: &buf)
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterUInt64.write(value.mtime, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntry_lift(_ buf: RustBuffer) throws -> DirEntry {
    return try FfiConverterTypeDirEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntry_lower(_ value: DirEntry) -> RustBuffer {
    return FfiConverterTypeDirEntry.lower(value)
}


public struct FileStat {
    public var size: UInt64
    public var mtime: UInt64
    public var kind: StatKind

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(size: UInt64, mtime: UInt64, kind: StatKind) {
        self.size = size
        self.mtime = mtime
        self.kind = kind
    }
}



extension FileStat: Equatable, Hashable {
    public static func ==(lhs: FileStat, rhs: FileStat) -> Bool {
        if lhs.size != rhs.size {
            return false
        }
        if lhs.mtime != rhs.mtime {
            return false
        }
        if lhs.kind != rhs.kind {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(size)
        hasher.combine(mtime)
        hasher.combine(kind)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFileStat: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FileStat {
        return
            try FileStat(
                size: FfiConverterUInt64.read(from: &buf), 
                mtime: FfiConverterUInt64.read(from: &buf), 
                kind: FfiConverterTypeStatKind.read(from: &buf)
        )
    }

    public static func write(_ value: FileStat, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterUInt64.write(value.mtime, into: &buf)
        FfiConverterTypeStatKind.write(value.kind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileStat_lift(_ buf: RustBuffer) throws -> FileStat {
    return try FfiConverterTypeFileStat.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFileStat_lower(_ value: FileStat) -> RustBuffer {
    return FfiConverterTypeFileStat.lower(value)
}


public struct GrepHit {
    public var path: String
    public var rel: String
    public var line: UInt64
    public var text: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, rel: String, line: UInt64, text: String) {
        self.path = path
        self.rel = rel
        self.line = line
        self.text = text
    }
}



extension GrepHit: Equatable, Hashable {
    public static func ==(lhs: GrepHit, rhs: GrepHit) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.rel != rhs.rel {
            return false
        }
        if lhs.line != rhs.line {
            return false
        }
        if lhs.text != rhs.text {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(rel)
        hasher.combine(line)
        hasher.combine(text)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrepHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GrepHit {
        return
            try GrepHit(
                path: FfiConverterString.read(from: &buf), 
                rel: FfiConverterString.read(from: &buf), 
                line: FfiConverterUInt64.read(from: &buf), 
                text: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: GrepHit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.rel, into: &buf)
        FfiConverterUInt64.write(value.line, into: &buf)
        FfiConverterString.write(value.text, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrepHit_lift(_ buf: RustBuffer) throws -> GrepHit {
    return try FfiConverterTypeGrepHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrepHit_lower(_ value: GrepHit) -> RustBuffer {
    return FfiConverterTypeGrepHit.lower(value)
}


public struct GrepResponse {
    public var hits: [GrepHit]
    public var truncated: Bool
    public var filesScanned: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(hits: [GrepHit], truncated: Bool, filesScanned: UInt64) {
        self.hits = hits
        self.truncated = truncated
        self.filesScanned = filesScanned
    }
}



extension GrepResponse: Equatable, Hashable {
    public static func ==(lhs: GrepResponse, rhs: GrepResponse) -> Bool {
        if lhs.hits != rhs.hits {
            return false
        }
        if lhs.truncated != rhs.truncated {
            return false
        }
        if lhs.filesScanned != rhs.filesScanned {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hits)
        hasher.combine(truncated)
        hasher.combine(filesScanned)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGrepResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GrepResponse {
        return
            try GrepResponse(
                hits: FfiConverterSequenceTypeGrepHit.read(from: &buf), 
                truncated: FfiConverterBool.read(from: &buf), 
                filesScanned: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: GrepResponse, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeGrepHit.write(value.hits, into: &buf)
        FfiConverterBool.write(value.truncated, into: &buf)
        FfiConverterUInt64.write(value.filesScanned, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrepResponse_lift(_ buf: RustBuffer) throws -> GrepResponse {
    return try FfiConverterTypeGrepResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGrepResponse_lower(_ value: GrepResponse) -> RustBuffer {
    return FfiConverterTypeGrepResponse.lower(value)
}


public struct SearchHit {
    public var path: String
    public var rel: String
    public var name: String
    public var isDir: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, rel: String, name: String, isDir: Bool) {
        self.path = path
        self.rel = rel
        self.name = name
        self.isDir = isDir
    }
}



extension SearchHit: Equatable, Hashable {
    public static func ==(lhs: SearchHit, rhs: SearchHit) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.rel != rhs.rel {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.isDir != rhs.isDir {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(rel)
        hasher.combine(name)
        hasher.combine(isDir)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchHit: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchHit {
        return
            try SearchHit(
                path: FfiConverterString.read(from: &buf), 
                rel: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                isDir: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SearchHit, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterString.write(value.rel, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterBool.write(value.isDir, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lift(_ buf: RustBuffer) throws -> SearchHit {
    return try FfiConverterTypeSearchHit.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchHit_lower(_ value: SearchHit) -> RustBuffer {
    return FfiConverterTypeSearchHit.lower(value)
}


public struct SearchResult {
    public var hits: [SearchHit]
    public var truncated: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(hits: [SearchHit], truncated: Bool) {
        self.hits = hits
        self.truncated = truncated
    }
}



extension SearchResult: Equatable, Hashable {
    public static func ==(lhs: SearchResult, rhs: SearchResult) -> Bool {
        if lhs.hits != rhs.hits {
            return false
        }
        if lhs.truncated != rhs.truncated {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(hits)
        hasher.combine(truncated)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SearchResult {
        return
            try SearchResult(
                hits: FfiConverterSequenceTypeSearchHit.read(from: &buf), 
                truncated: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: SearchResult, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeSearchHit.write(value.hits, into: &buf)
        FfiConverterBool.write(value.truncated, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lift(_ buf: RustBuffer) throws -> SearchResult {
    return try FfiConverterTypeSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSearchResult_lower(_ value: SearchResult) -> RustBuffer {
    return FfiConverterTypeSearchResult.lower(value)
}


public enum BunError {

    
    
    case Error(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBunError: FfiConverterRustBuffer {
    typealias SwiftType = BunError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BunError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Error(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BunError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Error(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension BunError: Equatable, Hashable {}

extension BunError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum EntryKind {
    
    case file
    case dir
    case symlink
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntryKind: FfiConverterRustBuffer {
    typealias SwiftType = EntryKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntryKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .file
        
        case 2: return .dir
        
        case 3: return .symlink
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EntryKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .file:
            writeInt(&buf, Int32(1))
        
        
        case .dir:
            writeInt(&buf, Int32(2))
        
        
        case .symlink:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntryKind_lift(_ buf: RustBuffer) throws -> EntryKind {
    return try FfiConverterTypeEntryKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntryKind_lower(_ value: EntryKind) -> RustBuffer {
    return FfiConverterTypeEntryKind.lower(value)
}



extension EntryKind: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum ReadResult {
    
    case text(content: String, size: UInt64
    )
    case binary(size: UInt64
    )
    case tooLarge(size: UInt64, limit: UInt64
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeReadResult: FfiConverterRustBuffer {
    typealias SwiftType = ReadResult

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ReadResult {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .text(content: try FfiConverterString.read(from: &buf), size: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 2: return .binary(size: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 3: return .tooLarge(size: try FfiConverterUInt64.read(from: &buf), limit: try FfiConverterUInt64.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ReadResult, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .text(content,size):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(content, into: &buf)
            FfiConverterUInt64.write(size, into: &buf)
            
        
        case let .binary(size):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(size, into: &buf)
            
        
        case let .tooLarge(size,limit):
            writeInt(&buf, Int32(3))
            FfiConverterUInt64.write(size, into: &buf)
            FfiConverterUInt64.write(limit, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReadResult_lift(_ buf: RustBuffer) throws -> ReadResult {
    return try FfiConverterTypeReadResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeReadResult_lower(_ value: ReadResult) -> RustBuffer {
    return FfiConverterTypeReadResult.lower(value)
}



extension ReadResult: Equatable, Hashable {}



// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum StatKind {
    
    case file
    case dir
    case symlink
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStatKind: FfiConverterRustBuffer {
    typealias SwiftType = StatKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StatKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .file
        
        case 2: return .dir
        
        case 3: return .symlink
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StatKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .file:
            writeInt(&buf, Int32(1))
        
        
        case .dir:
            writeInt(&buf, Int32(2))
        
        
        case .symlink:
            writeInt(&buf, Int32(3))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatKind_lift(_ buf: RustBuffer) throws -> StatKind {
    return try FfiConverterTypeStatKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStatKind_lower(_ value: StatKind) -> RustBuffer {
    return FfiConverterTypeStatKind.lower(value)
}



extension StatKind: Equatable, Hashable {}






public protocol PtyCallback : AnyObject {
    
    func onData(id: UInt32, data: Data) 
    
    func onExit(id: UInt32, exitCode: Int32) 
    
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfacePtyCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfacePtyCallback = UniffiVTableCallbackInterfacePtyCallback(
        onData: { (
            uniffiHandle: UInt64,
            id: UInt32,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfacePtyCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onData(
                     id: try FfiConverterUInt32.lift(id),
                     data: try FfiConverterData.lift(data)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onExit: { (
            uniffiHandle: UInt64,
            id: UInt32,
            exitCode: Int32,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterCallbackInterfacePtyCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onExit(
                     id: try FfiConverterUInt32.lift(id),
                     exitCode: try FfiConverterInt32.lift(exitCode)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterCallbackInterfacePtyCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface PtyCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitPtyCallback() {
    uniffi_bunnyshell_core_fn_init_callback_vtable_ptycallback(&UniffiCallbackInterfacePtyCallback.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfacePtyCallback {
    fileprivate static var handleMap = UniffiHandleMap<PtyCallback>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfacePtyCallback : FfiConverter {
    typealias SwiftType = PtyCallback
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDirEntry: FfiConverterRustBuffer {
    typealias SwiftType = [DirEntry]

    public static func write(_ value: [DirEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDirEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DirEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [DirEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDirEntry.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeGrepHit: FfiConverterRustBuffer {
    typealias SwiftType = [GrepHit]

    public static func write(_ value: [GrepHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeGrepHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [GrepHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [GrepHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeGrepHit.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSearchHit: FfiConverterRustBuffer {
    typealias SwiftType = [SearchHit]

    public static func write(_ value: [SearchHit], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSearchHit.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SearchHit] {
        let len: Int32 = try readInt(&buf)
        var seq = [SearchHit]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSearchHit.read(from: &buf))
        }
        return seq
    }
}
public func fsCreateDir(path: String)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_create_dir(
        FfiConverterString.lower(path),$0
    )
}
}
public func fsCreateFile(path: String)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_create_file(
        FfiConverterString.lower(path),$0
    )
}
}
public func fsDelete(path: String)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_delete(
        FfiConverterString.lower(path),$0
    )
}
}
public func fsGrep(pattern: String, root: String, glob: [String]?, caseInsensitive: Bool?, maxResults: UInt32?)throws  -> GrepResponse {
    return try  FfiConverterTypeGrepResponse.lift(try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_grep(
        FfiConverterString.lower(pattern),
        FfiConverterString.lower(root),
        FfiConverterOptionSequenceString.lower(glob),
        FfiConverterOptionBool.lower(caseInsensitive),
        FfiConverterOptionUInt32.lower(maxResults),$0
    )
})
}
public func fsReadDir(path: String, showHidden: Bool)throws  -> [DirEntry] {
    return try  FfiConverterSequenceTypeDirEntry.lift(try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_read_dir(
        FfiConverterString.lower(path),
        FfiConverterBool.lower(showHidden),$0
    )
})
}
public func fsReadFile(path: String)throws  -> ReadResult {
    return try  FfiConverterTypeReadResult.lift(try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_read_file(
        FfiConverterString.lower(path),$0
    )
})
}
public func fsRename(fromPath: String, toPath: String)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_rename(
        FfiConverterString.lower(fromPath),
        FfiConverterString.lower(toPath),$0
    )
}
}
public func fsSearch(root: String, query: String, limit: UInt32?, showHidden: Bool?)throws  -> SearchResult {
    return try  FfiConverterTypeSearchResult.lift(try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_search(
        FfiConverterString.lower(root),
        FfiConverterString.lower(query),
        FfiConverterOptionUInt32.lower(limit),
        FfiConverterOptionBool.lower(showHidden),$0
    )
})
}
public func fsWriteFile(path: String, content: String)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_fs_write_file(
        FfiConverterString.lower(path),
        FfiConverterString.lower(content),$0
    )
}
}
public func loadWorkspaceState()throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_load_workspace_state($0
    )
})
}
public func saveWorkspaceState(stateJson: String)throws  {try rustCallWithError(FfiConverterTypeBunError.lift) {
    uniffi_bunnyshell_core_fn_func_save_workspace_state(
        FfiConverterString.lower(stateJson),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_bunnyshell_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_create_dir() != 20207) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_create_file() != 23487) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_delete() != 4705) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_grep() != 7091) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_read_dir() != 8018) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_read_file() != 28018) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_rename() != 42905) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_search() != 20148) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_fs_write_file() != 43275) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_load_workspace_state() != 61672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_func_save_workspace_state() != 7383) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_ptymanager_close() != 8736) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_ptymanager_resize() != 25250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_ptymanager_spawn() != 22674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_ptymanager_write() != 465) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_terminalrenderer_render() != 26713) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_terminalrenderer_resize() != 33832) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_constructor_ptymanager_new() != 26253) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_constructor_terminalrenderer_new() != 13568) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_ptycallback_on_data() != 12852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bunnyshell_core_checksum_method_ptycallback_on_exit() != 59276) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitPtyCallback()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all